<?php
require_once __DIR__.'/../models/Prorroga.php';require_once __DIR__.'/../helpers/Csrf.php';require_once __DIR__.'/../helpers/PeriodoHelper.php';
class AdminProrrogaController
{
 private Prorroga $m;public function __construct(mysqli $c){$this->m=new Prorroga($c);}
 public function index():void{$this->admin();$b=trim((string)($_GET['buscar']??''));$p=preg_match('/^\d{4}-\d{2}$/',(string)($_GET['periodo']??''))?$_GET['periodo']:'';$e=in_array($_GET['estado']??'', ['Vigente','Vencida','Finalizada'],true)?$_GET['estado']:'';$pg=filter_var($_GET['pagina']??1,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]])?:1;$n=10;$total=$this->m->contarParaAdministrador($b,$p,$e);$paginas=max(1,(int)ceil($total/$n));$pg=min($pg,$paginas);$prorrogas=$this->m->listarParaAdministrador($b,$p,$e,$n,($pg-1)*$n);$rutaAdminActiva='admin-prorrogas';$flash=$this->flashGet();require __DIR__.'/../views/admin/prorrogas/index.php';}
 public function crear():void{$this->admin();$adeudos=$this->m->obtenerAdeudosElegibles();$preseleccion=$this->id($_GET['id_adeudo']??null);$rutaAdminActiva='admin-prorrogas';$csrfToken=Csrf::token();require __DIR__.'/../views/admin/prorrogas/crear.php';}
 public function guardar():void{$this->admin();if($_SERVER['REQUEST_METHOD']!=='POST'){http_response_code(405);exit;}if(!Csrf::validar($_POST['csrf_token']??null)){$this->flash('error','Token de seguridad inválido.');$this->go('admin-prorroga-crear');}$id=$this->id($_POST['id_adeudo']??null);$a=$id?$this->m->buscarAdeudoElegiblePorId($id):null;if(!$a){$this->flash('error','Adeudo no encontrado.');$this->go('admin-prorroga-crear');}if($a['estado']!=='Pendiente'){$this->flash('error','El adeudo ya fue pagado.');$this->go('admin-prorroga-crear');}$fecha=(string)($_POST['nueva_fecha']??'');$f=DateTimeImmutable::createFromFormat('!Y-m-d',$fecha);if(!$f||$f->format('Y-m-d')!==$fecha||$fecha<=$a['fecha_limite']){$this->flash('error','La nueva fecha debe ser posterior a la fecha límite actual.');$this->go('admin-prorroga-crear');}if($fecha<(new DateTimeImmutable('today'))->format('Y-m-d')){$this->flash('error','La nueva fecha no puede estar vencida.');$this->go('admin-prorroga-crear');}$motivo=trim((string)($_POST['motivo']??''));$len=function_exists('mb_strlen')?mb_strlen($motivo,'UTF-8'):strlen($motivo);if($len<5||$len>255){$this->flash('error','El motivo debe contener al menos 5 caracteres.');$this->go('admin-prorroga-crear');}$nuevo=$this->m->aplicar($id,$a['fecha_limite'],$fecha,$motivo,(int)$_SESSION['id_usuario']);$this->flash($nuevo?'exito':'error',$nuevo?'Prórroga aplicada correctamente.':'No fue posible completar la operación.');$this->go($nuevo?'admin-prorroga-ver&id='.$nuevo:'admin-prorroga-crear');}
 public function ver():void{$this->admin();$id=$this->id($_GET['id']??null);$prorroga=$id?$this->m->buscarDetallePorId($id):null;if(!$prorroga){$this->flash('error','Adeudo no encontrado.');$this->go('admin-prorrogas');}$rutaAdminActiva='admin-prorrogas';require __DIR__.'/../views/admin/prorrogas/ver.php';}
 private function admin():void{if(!isset($_SESSION['id_usuario'])||($_SESSION['rol']??'')!=='Administrador')$this->go('login-admin');}private function id(mixed$v):int{return filter_var($v,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]])?:0;}private function flash(string$t,string$x):void{$_SESSION['flash']=['tipo'=>$t,'mensaje'=>$x];}private function flashGet():?array{$f=$_SESSION['flash']??null;unset($_SESSION['flash']);return is_array($f)?$f:null;}private function go(string$r):never{header('Location: '.BASE_URL.'/index.php?ruta='.$r);exit;}
}
