<?php
require_once __DIR__.'/../models/Aclaracion.php';require_once __DIR__.'/../models/Alumno.php';require_once __DIR__.'/../helpers/Csrf.php';require_once __DIR__.'/../helpers/PeriodoHelper.php';
class AdminAclaracionController
{
 private Aclaracion $m;private Alumno $alumnoModel;private array $tipos=['Pago no reflejado','Importe incorrecto','Adeudo duplicado','Recargo incorrecto','Comprobante no recibido','Otro'];public function __construct(mysqli$c){$this->m=new Aclaracion($c);$this->alumnoModel=new Alumno($c);}
 public function index():void{$this->admin();$b=trim((string)($_GET['buscar']??''));$tipo=in_array($_GET['tipo']??'',$this->tipos,true)?$_GET['tipo']:'';$estado=in_array($_GET['estado']??'', ['Abierta','En revisión','Resuelta','Rechazada'],true)?$_GET['estado']:'';$pg=filter_var($_GET['pagina']??1,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]])?:1;$n=10;$total=$this->m->contarParaAdministrador($b,$tipo,$estado);$paginas=max(1,(int)ceil($total/$n));$pg=min($pg,$paginas);$aclaraciones=$this->m->listarParaAdministrador($b,$tipo,$estado,$n,($pg-1)*$n);$tipos=$this->tipos;$rutaAdminActiva='admin-aclaraciones';$flash=$this->flashGet();require __DIR__.'/../views/admin/aclaraciones/index.php';}
 public function crear():void{$this->admin();$alumnos=$this->alumnoModel->listarActivosParaSelector();$relaciones=$this->m->relacionesParaFormulario();$tipos=$this->tipos;$csrfToken=Csrf::token();$rutaAdminActiva='admin-aclaraciones';require __DIR__.'/../views/admin/aclaraciones/crear.php';}
 public function guardar():void{$this->post('admin-aclaracion-crear');$id=$this->id($_POST['id_alumno']??null);$tipo=(string)($_POST['tipo']??'');$asunto=trim((string)($_POST['asunto']??''));$descripcion=trim((string)($_POST['descripcion']??''));if(!$id||!$this->m->alumnoActivo($id)){$this->flash('error','Alumno no encontrado.');$this->go('admin-aclaracion-crear');}if(!in_array($tipo,$this->tipos,true)||$asunto===''||strlen($asunto)>150||strlen($descripcion)<10){$this->flash('error','No fue posible completar la operación.');$this->go('admin-aclaracion-crear');}$adeudo=$this->id($_POST['id_adeudo']??null)?:null;$pago=$this->id($_POST['id_pago']??null)?:null;if($adeudo&&!$this->m->relacionPertenece('adeudos','id_adeudo',$adeudo,$id)){$this->flash('error','El adeudo no pertenece al alumno.');$this->go('admin-aclaracion-crear');}if($pago&&!$this->m->relacionPertenece('pagos','id_pago',$pago,$id)){$this->flash('error','El pago no pertenece al alumno.');$this->go('admin-aclaracion-crear');}$nuevo=$this->m->crear(['id_alumno'=>$id,'id_adeudo'=>$adeudo,'id_pago'=>$pago,'tipo'=>$tipo,'asunto'=>$asunto,'descripcion'=>$descripcion,'registrada_por'=>(int)$_SESSION['id_usuario']]);$this->flash($nuevo?'exito':'error',$nuevo?'Aclaración registrada correctamente.':'No fue posible completar la operación.');$this->go($nuevo?'admin-aclaracion-ver&id='.$nuevo:'admin-aclaracion-crear');}
 public function ver():void{$this->admin();$id=$this->id($_GET['id']??null);$aclaracion=$id?$this->m->buscarDetallePorId($id):null;if(!$aclaracion){$this->flash('error','Aclaración no encontrada.');$this->go('admin-aclaraciones');}$csrfToken=Csrf::token();$rutaAdminActiva='admin-aclaraciones';$flash=$this->flashGet();require __DIR__.'/../views/admin/aclaraciones/ver.php';}
 public function iniciarRevision():void{$this->procesar('revision');}public function resolver():void{$this->procesar('resolver');}public function rechazar():void{$this->procesar('rechazar');}
 private function procesar(string$accion):void{$this->post('admin-aclaraciones');$id=$this->id($_POST['id_aclaracion']??null);$respuesta=trim((string)($_POST['respuesta']??''));if(in_array($accion,['resolver','rechazar'],true)&&((function_exists('mb_strlen')?mb_strlen($respuesta,'UTF-8'):strlen($respuesta))<10||strlen($respuesta)>1000)){$this->flash('error','La respuesta es obligatoria.');$this->go('admin-aclaracion-ver&id='.$id);}$admin=(int)$_SESSION['id_usuario'];$ok=$accion==='revision'?$this->m->marcarEnRevision($id,$admin):($accion==='resolver'?$this->m->resolver($id,$admin,$respuesta):$this->m->rechazar($id,$admin,$respuesta));$mensajes=['revision'=>'Aclaración marcada En revisión.','resolver'=>'Aclaración resuelta correctamente.','rechazar'=>'Aclaración rechazada correctamente.'];$this->flash($ok?'exito':'error',$ok?$mensajes[$accion]:'Esta aclaración ya fue atendida.');$this->go('admin-aclaracion-ver&id='.$id);}
 private function post(string$r):void{$this->admin();if($_SERVER['REQUEST_METHOD']!=='POST'){http_response_code(405);exit;}if(!Csrf::validar($_POST['csrf_token']??null)){$this->flash('error','Token de seguridad inválido.');$this->go($r);}}private function admin():void{if(!isset($_SESSION['id_usuario'])||($_SESSION['rol']??'')!=='Administrador')$this->go('login-admin');}private function id(mixed$v):int{return filter_var($v,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]])?:0;}private function flash(string$t,string$x):void{$_SESSION['flash']=['tipo'=>$t,'mensaje'=>$x];}private function flashGet():?array{$f=$_SESSION['flash']??null;unset($_SESSION['flash']);return is_array($f)?$f:null;}private function go(string$r):never{header('Location: '.BASE_URL.'/index.php?ruta='.$r);exit;}
}
