<?php
require_once __DIR__.'/../models/Reporte.php';require_once __DIR__.'/../helpers/PeriodoHelper.php';
// Controlador de solo lectura para reportes, CSV e impresión.
class AdminReporteController
{
 private Reporte $m;private bool $rangoInvalido=false;private array $tipos=['pagos','adeudos','alumnos','prorrogas','aclaraciones'];
 public function __construct(mysqli$c){$this->m=new Reporte($c);}
 public function index():void{$this->admin();$rutaAdminActiva='admin-reportes';require __DIR__.'/../views/admin/reportes/index.php';}
 public function pagos():void{$this->mostrar('pagos');}public function adeudos():void{$this->mostrar('adeudos');}public function alumnos():void{$this->mostrar('alumnos');}public function prorrogas():void{$this->mostrar('prorrogas');}public function aclaraciones():void{$this->mostrar('aclaraciones');}
 private function mostrar(string$tipo):void{$this->admin();$filtros=$this->filtros($tipo);$pagina=filter_var($_GET['pagina']??1,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]])?:1;$errorRango=$this->rangoInvalido;$total=$errorRango?0:$this->contar($tipo,$filtros);$paginas=max(1,(int)ceil($total/25));$pagina=min($pagina,$paginas);$registros=$errorRango?[]:$this->obtener($tipo,$filtros,25,($pagina-1)*25);$resumen=$errorRango?[]:$this->resumen($tipo,$filtros);$meta=$this->meta($tipo);$opciones=$tipo==='alumnos'?$this->m->opcionesAlumnos():[];$rutaAdminActiva='admin-reportes';require __DIR__.'/../views/admin/reportes/'.$tipo.'.php';}
 public function exportar():void{$this->admin();$tipo=$this->tipo();$f=$this->filtros($tipo);$rows=$this->obtener($tipo,$f,0,0);$meta=$this->meta($tipo);header('Content-Type: text/csv; charset=UTF-8');header('Content-Disposition: attachment; filename="reporte_'.$tipo.'_'.date('Ymd_His').'.csv"');echo "\xEF\xBB\xBF";$out=fopen('php://output','w');fputcsv($out,array_values($meta['columnas']));foreach($rows as$row){$line=[];foreach(array_keys($meta['columnas'])as$k)$line[]=$this->csv($this->valor($k,$row[$k]??''));fputcsv($out,$line);}fclose($out);exit;}
 public function imprimir():void{$this->admin();$tipo=$this->tipo();$filtros=$this->filtros($tipo);$registros=$this->obtener($tipo,$filtros,0,0);$resumen=$this->resumen($tipo,$filtros);$meta=$this->meta($tipo);$administrador=(string)($_SESSION['nombre_usuario']??'Administrador');require __DIR__.'/../views/admin/reportes/imprimir.php';}
 private function filtros(string$t):array{$f=['buscar'=>trim((string)($_GET['buscar']??'')),'desde'=>$this->fecha($_GET['desde']??''),'hasta'=>$this->fecha($_GET['hasta']??''),'periodo'=>preg_match('/^\d{4}-\d{2}$/',(string)($_GET['periodo']??''))?(string)$_GET['periodo']:'','estado'=>trim((string)($_GET['estado']??'')),'origen'=>trim((string)($_GET['origen']??'')),'metodo'=>trim((string)($_GET['metodo']??'')),'recargo'=>in_array($_GET['recargo']??'',['con','sin'],true)?$_GET['recargo']:'','carrera'=>trim((string)($_GET['carrera']??'')),'grupo'=>trim((string)($_GET['grupo']??'')),'tipo'=>trim((string)($_GET['tipo_aclaracion']??''))];if($f['desde']&&$f['hasta']&&$f['desde']>$f['hasta']){$f['desde']=$f['hasta']='';}return$f;}
 private function fecha(mixed$v):string{$s=is_string($v)?$v:'';$d=DateTimeImmutable::createFromFormat('!Y-m-d',$s);return$d&&$d->format('Y-m-d')===$s?$s:'';}
 private function obtener(string$t,array$f,int$l,int$o):array{$m='obtener'.ucfirst($t);return$this->m->$m($f,$l,$o);}private function contar(string$t,array$f):int{$m='contar'.ucfirst($t);return$this->m->$m($f);}private function resumen(string$t,array$f):array{$m='obtenerResumen'.ucfirst($t);return$this->m->$m($f);}
 private function tipo():string{$t=(string)($_GET['tipo']??'');if(!in_array($t,$this->tipos,true)){http_response_code(400);exit('Tipo de reporte no válido.');}return$t;}
 private function meta(string$t):array{$m=[
 'pagos'=>['titulo'=>'Reporte de Pagos','columnas'=>['folio'=>'Folio','fecha_pago'=>'Fecha','matricula'=>'Matrícula','nombre'=>'Alumno','periodo'=>'Periodo','metodo_pago'=>'Método','origen'=>'Origen','estado_validacion'=>'Estado','total_pagado'=>'Importe']],
 'adeudos'=>['titulo'=>'Reporte de Adeudos','columnas'=>['matricula'=>'Matrícula','nombre'=>'Alumno','periodo'=>'Periodo','fecha_limite'=>'Fecha límite','mensualidad'=>'Mensualidad','aportacion_tsu'=>'Aportación TSU','atraso'=>'Atraso','recargo'=>'Recargo','total'=>'Total','estado'=>'Estado']],
 'alumnos'=>['titulo'=>'Reporte de Alumnos','columnas'=>['matricula'=>'Matrícula','nombre'=>'Nombre','correo'=>'Correo','carrera'=>'Carrera','grupo'=>'Grupo','estado'=>'Estado']],
 'prorrogas'=>['titulo'=>'Reporte de Prórrogas','columnas'=>['matricula'=>'Matrícula','nombre'=>'Alumno','periodo'=>'Periodo','fecha_limite_anterior'=>'Fecha anterior','nueva_fecha_limite'=>'Nueva fecha','estado_visual'=>'Estado','motivo'=>'Motivo','administrador'=>'Autorizada por','fecha_aplicacion'=>'Fecha de aplicación']],
 'aclaraciones'=>['titulo'=>'Reporte de Aclaraciones','columnas'=>['folio'=>'Folio','fecha_registro'=>'Fecha','matricula'=>'Matrícula','nombre'=>'Alumno','tipo'=>'Tipo','asunto'=>'Asunto','estado'=>'Estado','atendida_por'=>'Atendida por','fecha_atencion'=>'Fecha de atención']]];return$m[$t];}
 public function valor(string$k,mixed$v):string{if(in_array($k,['mensualidad','aportacion_tsu','atraso','recargo','total','total_pagado'],true))return'$'.number_format((float)$v,2);if($k==='periodo')return PeriodoHelper::formatear((string)$v);if(str_contains($k,'fecha')&&$v){$d=new DateTimeImmutable((string)$v);return$d->format(strlen((string)$v)>10?'d/m/Y H:i':'d/m/Y');}return(string)($v?:'Pendiente');}
 private function csv(string$v):string{return preg_match('/^[=+\-@]/u',$v)?"'".$v:$v;}
 private function admin():void{if(!isset($_SESSION['id_usuario'])||($_SESSION['rol']??'')!=='Administrador'){header('Location: '.BASE_URL.'/index.php?ruta=login-admin');exit;}}
}
