<?php
require_once __DIR__.'/../models/Estadistica.php';require_once __DIR__.'/../helpers/PeriodoHelper.php';
class AdminEstadisticaController
{
 private bool $rangoInvalido=false;
 public function __construct(private mysqli$c){}
 public function index():void{$this->admin();[$inicio,$fin]=$this->rango();$periodo=preg_match('/^\d{4}-\d{2}$/',(string)($_GET['periodo']??''))?(string)$_GET['periodo']:null;$m=new Estadistica($this->c);try{$indicadores=$m->obtenerIndicadoresGenerales($inicio,$fin);$ingresos=$m->obtenerIngresosPorMes($inicio,$fin);$pagosEstado=$m->obtenerPagosPorEstado($inicio,$fin);$metodos=$m->obtenerPagosPorMetodo($inicio,$fin);$origenes=$m->obtenerPagosPorOrigen($inicio,$fin);$adeudosEstado=$m->obtenerAdeudosPorEstado($periodo);$montosAdeudos=$m->obtenerMontosAdeudos($periodo);$alumnosEstado=$m->obtenerAlumnosPorEstado();$aclaracionesEstado=$m->obtenerAclaracionesPorEstado($inicio,$fin);$prorrogasEstado=$m->obtenerProrrogasPorEstado($inicio,$fin);$ultimosPagos=$m->obtenerUltimosPagosValidados();$periodos=$m->obtenerPeriodosDisponibles();$error='';}catch(Throwable$e){$indicadores=[];$ingresos=$pagosEstado=$metodos=$origenes=$adeudosEstado=$alumnosEstado=$aclaracionesEstado=$prorrogasEstado=$ultimosPagos=$periodos=[];$montosAdeudos=[];$error='No fue posible cargar las estadísticas.';}$rutaAdminActiva='admin-estadisticas';require __DIR__.'/../views/admin/estadisticas/index.php';}
 private function rango():array{$r=(string)($_GET['rango']??'');$h=new DateTimeImmutable('today');if($r==='mes')return[$h->format('Y-m-01'),$h->format('Y-m-d')];if($r==='3')return[$h->modify('-2 months')->format('Y-m-01'),$h->format('Y-m-d')];if($r==='6')return[$h->modify('-5 months')->format('Y-m-01'),$h->format('Y-m-d')];if($r==='anio')return[$h->format('Y-01-01'),$h->format('Y-m-d')];$i=$this->fecha($_GET['fecha_inicio']??null);$f=$this->fecha($_GET['fecha_fin']??null);return[$i,$f];}
 private function fecha(mixed$v):?string{$s=is_string($v)?$v:'';$d=DateTimeImmutable::createFromFormat('!Y-m-d',$s);return$d&&$d->format('Y-m-d')===$s?$s:null;}private function admin():void{if(!isset($_SESSION['id_usuario'])||($_SESSION['rol']??'')!=='Administrador'){header('Location: '.BASE_URL.'/index.php?ruta=login-admin');exit;}}
}
