<?php
require_once __DIR__.'/../models/Pago.php';require_once __DIR__.'/../models/Adeudo.php';require_once __DIR__.'/../helpers/Csrf.php';require_once __DIR__.'/../helpers/PeriodoHelper.php';
class AdminPagoController
{
 private Pago $modelo;private Adeudo $adeudoModelo;public function __construct(mysqli $c){$this->modelo=new Pago($c);$this->adeudoModelo=new Adeudo($c);}
 public function index():void{$this->admin();$b=trim((string)($_GET['buscar']??''));$p=preg_match('/^\d{4}-\d{2}$/',(string)($_GET['periodo']??''))?(string)$_GET['periodo']:'';$e=in_array($_GET['estado']??'', ['Pendiente','Validado','Rechazado'],true)?$_GET['estado']:'';$o=in_array($_GET['origen']??'', ['Portal Alumno','Manual Administrador'],true)?$_GET['origen']:'';$pg=filter_var($_GET['pagina']??1,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]])?:1;$n=10;$total=$this->modelo->contarParaAdministrador($b,$p,$e,$o);$paginas=max(1,(int)ceil($total/$n));$pg=min($pg,$paginas);$pagos=$this->modelo->listarParaAdministrador($b,$p,$e,$o,$n,($pg-1)*$n);$rutaAdminActiva='admin-pagos';$csrfToken=Csrf::token();$flash=$this->flashGet();require __DIR__.'/../views/admin/pagos/index.php';}
 public function ver():void{$this->admin();$pago=$this->detalle();$periodoTexto=PeriodoHelper::formatear($pago['periodo']);$rutaAdminActiva='admin-pagos';$csrfToken=Csrf::token();$flash=$this->flashGet();require __DIR__.'/../views/admin/pagos/ver.php';}
 public function crearManual():void{$this->admin();$this->adeudoModelo->actualizarRecargosVencidos();$adeudos=$this->modelo->listarAdeudosPendientesParaPagoManual();$rutaAdminActiva='admin-pagos';$csrfToken=Csrf::token();require __DIR__.'/../views/admin/pagos/registrar_manual.php';}
 public function guardarManual():void{$this->post('admin-pago-manual');$id=$this->id($_POST['id_adeudo']??null);$metodo=in_array($_POST['metodo']??'', ['Efectivo','Transferencia','Depósito','Otro'],true)?$_POST['metodo']:'';if(!$id||!$metodo){$this->flash('error','Adeudo no encontrado.');$this->go('admin-pago-manual');}$ref=trim((string)($_POST['referencia']??''));$obs=trim((string)($_POST['observaciones']??''));try{$nuevo=$this->modelo->registrarPagoManual($id,(int)$_SESSION['id_usuario'],$metodo,$ref,$obs);}catch(Throwable $e){$nuevo=false;}$this->flash($nuevo?'exito':'error',$nuevo?'Pago manual registrado correctamente.':'Ya existe un pago pendiente o validado para este adeudo.');$this->go($nuevo?'admin-pago-ver&id='.$nuevo:'admin-pago-manual');}
 public function validar():void{$this->post('admin-pagos');$id=$this->id($_POST['id_pago']??null);$ok=$id&&$this->modelo->validarPago($id,(int)$_SESSION['id_usuario']);$this->flash($ok?'exito':'error',$ok?'Pago validado correctamente.':'Este pago ya fue procesado.');$this->go($id?'admin-pago-ver&id='.$id:'admin-pagos');}
 public function rechazar():void{$this->post('admin-pagos');$id=$this->id($_POST['id_pago']??null);$m=trim((string)($_POST['motivo']??''));$len=function_exists('mb_strlen')?mb_strlen($m,'UTF-8'):strlen($m);if($len<5||$len>255){$this->flash('error','El motivo del rechazo es obligatorio.');$this->go($id?'admin-pago-ver&id='.$id:'admin-pagos');}$ok=$this->modelo->rechazarPago($id,(int)$_SESSION['id_usuario'],$m);$this->flash($ok?'exito':'error',$ok?'Pago rechazado correctamente.':'Este pago ya fue procesado.');$this->go('admin-pago-ver&id='.$id);}
 private function detalle():array{$id=$this->id($_GET['id']??null);$p=$id?$this->modelo->buscarDetalleAdministrativo($id):null;if(!$p){$this->flash('error','Pago no encontrado.');$this->go('admin-pagos');}return $p;}
 private function post(string $r):void{$this->admin();$this->adeudoModelo->actualizarRecargosVencidos();if($_SERVER['REQUEST_METHOD']!=='POST'){http_response_code(405);exit;}if(!Csrf::validar($_POST['csrf_token']??null)){$this->flash('error','Token de seguridad inválido.');$this->go($r);}}
 private function admin():void{if(!isset($_SESSION['id_usuario'])||($_SESSION['rol']??'')!=='Administrador')$this->go('login-admin');}
 private function id(mixed $v):int{return filter_var($v,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]])?:0;}private function flash(string $t,string $m):void{$_SESSION['flash']=['tipo'=>$t,'mensaje'=>$m];}private function flashGet():?array{$f=$_SESSION['flash']??null;unset($_SESSION['flash']);return is_array($f)?$f:null;}private function go(string $r):never{header('Location: '.BASE_URL.'/index.php?ruta='.$r);exit;}
}
