<?php
// Modelo: registro y atención de aclaraciones administrativas.
class Aclaracion
{
 private mysqli $conexion;public function __construct(mysqli $c){$this->conexion=$c;}
 private function base():string{return ' FROM aclaraciones c INNER JOIN alumnos a ON a.id_alumno=c.id_alumno LEFT JOIN adeudos d ON d.id_adeudo=c.id_adeudo LEFT JOIN pagos p ON p.id_pago=c.id_pago LEFT JOIN usuarios ur ON ur.id_usuario=c.registrada_por LEFT JOIN usuarios ua ON ua.id_usuario=c.atendida_por ';}
 public function listarParaAdministrador(string $b='',string $tipo='',string $estado='',int $limite=10,int $offset=0):array{$pat='%'.$b.'%';$s=$this->conexion->prepare('SELECT c.id_aclaracion,c.folio,a.matricula,a.nombre,a.correo,c.tipo,c.asunto,c.estado,c.fecha_registro,ua.nombre atendida_por_nombre'.$this->base().'WHERE (?="" OR c.folio LIKE ? OR a.matricula LIKE ? OR a.nombre LIKE ? OR a.correo LIKE ? OR c.asunto LIKE ?) AND (?="" OR c.tipo=?) AND (?="" OR c.estado=?) ORDER BY c.fecha_registro DESC,c.id_aclaracion DESC LIMIT ? OFFSET ?');$s->bind_param('ssssssssssii',$b,$pat,$pat,$pat,$pat,$pat,$tipo,$tipo,$estado,$estado,$limite,$offset);$s->execute();return$s->get_result()->fetch_all(MYSQLI_ASSOC);}
 public function contarParaAdministrador(string $b='',string $tipo='',string $estado=''):int{$pat='%'.$b.'%';$s=$this->conexion->prepare('SELECT COUNT(*) total'.$this->base().'WHERE (?="" OR c.folio LIKE ? OR a.matricula LIKE ? OR a.nombre LIKE ? OR a.correo LIKE ? OR c.asunto LIKE ?) AND (?="" OR c.tipo=?) AND (?="" OR c.estado=?)');$s->bind_param('ssssssssss',$b,$pat,$pat,$pat,$pat,$pat,$tipo,$tipo,$estado,$estado);$s->execute();return(int)($s->get_result()->fetch_assoc()['total']??0);}
 public function buscarDetallePorId(int $id,bool $lock=false):?array{$sql='SELECT c.*,a.matricula,a.nombre,a.correo,d.periodo,p.folio folio_pago,ur.nombre registrada_por_nombre,ua.nombre atendida_por_nombre'.$this->base().'WHERE c.id_aclaracion=?'.($lock?' FOR UPDATE':'');$s=$this->conexion->prepare($sql);$s->bind_param('i',$id);$s->execute();return$s->get_result()->fetch_assoc()?:null;}
 public function alumnosActivos():array{$s=$this->conexion->prepare('SELECT id_alumno,matricula,nombre,correo FROM alumnos WHERE estado="Activo" ORDER BY nombre');$s->execute();return$s->get_result()->fetch_all(MYSQLI_ASSOC);}
 public function relacionesAlumno(int $id):array{$a=$this->conexion->prepare('SELECT id_adeudo,periodo,total,estado FROM adeudos WHERE id_alumno=? ORDER BY periodo DESC');$a->bind_param('i',$id);$a->execute();$adeudos=$a->get_result()->fetch_all(MYSQLI_ASSOC);$p=$this->conexion->prepare('SELECT id_pago,folio,total_pagado,estado_validacion,fecha_pago FROM pagos WHERE id_alumno=? ORDER BY fecha_pago DESC');$p->bind_param('i',$id);$p->execute();$pagos=$p->get_result()->fetch_all(MYSQLI_ASSOC);return['adeudos'=>$adeudos,'pagos'=>$pagos];}
 public function relacionesParaFormulario():array{$a=$this->conexion->query('SELECT id_adeudo,id_alumno,periodo,total,estado FROM adeudos ORDER BY periodo DESC')->fetch_all(MYSQLI_ASSOC);$p=$this->conexion->query('SELECT id_pago,id_alumno,folio,total_pagado,estado_validacion,fecha_pago FROM pagos ORDER BY fecha_pago DESC')->fetch_all(MYSQLI_ASSOC);return['adeudos'=>$a,'pagos'=>$p];}
 public function alumnoActivo(int $id):bool{$s=$this->conexion->prepare('SELECT 1 FROM alumnos WHERE id_alumno=? AND estado="Activo"');$s->bind_param('i',$id);$s->execute();return$s->get_result()->fetch_assoc()!==null;}
 public function relacionPertenece(string $tabla,string $campo,int $idRelacion,int $idAlumno):bool{if(!in_array($tabla,['adeudos','pagos'],true)||!in_array($campo,['id_adeudo','id_pago'],true))return false;$sql="SELECT 1 FROM $tabla WHERE $campo=? AND id_alumno=?";$s=$this->conexion->prepare($sql);$s->bind_param('ii',$idRelacion,$idAlumno);$s->execute();return$s->get_result()->fetch_assoc()!==null;}
 public function crear(array $d):int|false{do{$folio='ACL-'.date('YmdHis').'-'.random_int(100,999);$q=$this->conexion->prepare('SELECT 1 FROM aclaraciones WHERE folio=?');$q->bind_param('s',$folio);$q->execute();}while($q->get_result()->fetch_assoc());$estado='Abierta';$s=$this->conexion->prepare('INSERT INTO aclaraciones(folio,id_alumno,id_adeudo,id_pago,tipo,asunto,descripcion,estado,registrada_por) VALUES(?,?,?,?,?,?,?,?,?)');$s->bind_param('siiissssi',$folio,$d['id_alumno'],$d['id_adeudo'],$d['id_pago'],$d['tipo'],$d['asunto'],$d['descripcion'],$estado,$d['registrada_por']);return$s->execute()?(int)$this->conexion->insert_id:false;}
 private function cambiar(int $id,int $admin,string $estado,?string $respuesta,bool $soloAbierta=false):bool{$this->conexion->begin_transaction();try{$a=$this->buscarDetallePorId($id,true);if(!$a||in_array($a['estado'],['Resuelta','Rechazada'],true)||($soloAbierta&&$a['estado']!=='Abierta'))throw new RuntimeException();$fecha=date('Y-m-d H:i:s');$s=$this->conexion->prepare('UPDATE aclaraciones SET estado=?,respuesta=?,atendida_por=?,fecha_atencion=? WHERE id_aclaracion=? AND estado NOT IN ("Resuelta","Rechazada")');$s->bind_param('ssisi',$estado,$respuesta,$admin,$fecha,$id);$s->execute();if($s->affected_rows!==1)throw new RuntimeException();$this->conexion->commit();return true;}catch(Throwable $e){$this->conexion->rollback();return false;}}
 public function marcarEnRevision(int $id,int $admin):bool{return$this->cambiar($id,$admin,'En revisión',null,true);}public function resolver(int $id,int $admin,string $r):bool{return$this->cambiar($id,$admin,'Resuelta',$r);}public function rechazar(int $id,int $admin,string $r):bool{return$this->cambiar($id,$admin,'Rechazada',$r);}
}
