<?php
// Modelo de solo lectura: agregados del panel de estadísticas.
class Estadistica
{
 public function __construct(private mysqli$c){}
 private function fechas(string$campo,?string$i,?string$f):array{return[' AND (? IS NULL OR DATE('.$campo.')>=?) AND (? IS NULL OR DATE('.$campo.')<=?)','ssss',[$i,$i,$f,$f]];}
 private function q(string$sql,string$t='',array$v=[]):mysqli_result{$s=$this->c->prepare($sql);if($t)$s->bind_param($t,...$v);$s->execute();return$s->get_result();}
 public function obtenerIndicadoresGenerales(?string$i=null,?string$f=null):array{[$w,$t,$v]=$this->fechas('fecha_pago',$i,$f);$p=$this->q('SELECT COALESCE(SUM(CASE WHEN estado_validacion="Validado" THEN total_pagado ELSE 0 END),0) recaudado,SUM(estado_validacion="Validado") pagos_validados FROM pagos WHERE 1'.$w,$t,$v)->fetch_assoc();$d=$this->c->query('SELECT COALESCE(SUM(CASE WHEN estado="Pendiente" THEN total ELSE 0 END),0) monto_pendiente,SUM(estado="Pendiente") adeudos_pendientes FROM adeudos')->fetch_assoc();$a=$this->c->query('SELECT SUM(estado="Activo") alumnos_activos FROM alumnos')->fetch_assoc();$c=$this->c->query('SELECT SUM(estado IN("Abierta","En revisión")) aclaraciones_pendientes FROM aclaraciones')->fetch_assoc();return array_merge($p,$d,$a,$c);}
 public function obtenerIngresosPorMes(?string$i=null,?string$f=null):array{[$w,$t,$v]=$this->fechas('fecha_pago',$i,$f);return$this->q('SELECT DATE_FORMAT(fecha_pago,"%Y-%m") periodo,SUM(total_pagado) total FROM pagos WHERE estado_validacion="Validado"'.$w.' GROUP BY DATE_FORMAT(fecha_pago,"%Y-%m") ORDER BY periodo',$t,$v)->fetch_all(MYSQLI_ASSOC);}
 public function obtenerPagosPorEstado(?string$i=null,?string$f=null):array{return$this->grupoPago('estado_validacion',$i,$f);}public function obtenerPagosPorMetodo(?string$i=null,?string$f=null):array{return$this->grupoPago('metodo_pago',$i,$f,true);}public function obtenerPagosPorOrigen(?string$i=null,?string$f=null):array{return$this->grupoPago('origen',$i,$f,true,true);}
 private function grupoPago(string$campo,?string$i,?string$f,bool$soloValidado=false,bool$monto=false):array{[$w,$t,$v]=$this->fechas('fecha_pago',$i,$f);$extra=$soloValidado?' AND estado_validacion="Validado"':'';return$this->q('SELECT '.$campo.' etiqueta,COUNT(*) cantidad'.($monto?',SUM(total_pagado) monto':'').' FROM pagos WHERE 1'.$extra.$w.' GROUP BY '.$campo.' ORDER BY cantidad DESC',$t,$v)->fetch_all(MYSQLI_ASSOC);}
 public function obtenerAdeudosPorEstado(?string$p=null):array{$s=$this->q('SELECT estado etiqueta,COUNT(*) cantidad FROM adeudos WHERE (? IS NULL OR DATE_FORMAT(periodo,"%Y-%m")=?) GROUP BY estado','ss',[$p,$p]);return$s->fetch_all(MYSQLI_ASSOC);}public function obtenerMontosAdeudos(?string$p=null):array{return$this->q('SELECT COALESCE(SUM(CASE WHEN estado="Pendiente" THEN total ELSE 0 END),0) pendiente,COALESCE(SUM(CASE WHEN estado="Pagado" THEN total ELSE 0 END),0) pagado,COALESCE(SUM(total),0) total,COALESCE(SUM(recargo),0) recargos FROM adeudos WHERE (? IS NULL OR DATE_FORMAT(periodo,"%Y-%m")=?)','ss',[$p,$p])->fetch_assoc();}
 public function obtenerAlumnosPorEstado():array{return$this->c->query('SELECT estado etiqueta,COUNT(*) cantidad FROM alumnos GROUP BY estado')->fetch_all(MYSQLI_ASSOC);}
 public function obtenerAclaracionesPorEstado(?string$i=null,?string$f=null):array{[$w,$t,$v]=$this->fechas('fecha_registro',$i,$f);return$this->q('SELECT estado etiqueta,COUNT(*) cantidad FROM aclaraciones WHERE 1'.$w.' GROUP BY estado',$t,$v)->fetch_all(MYSQLI_ASSOC);}
 public function obtenerProrrogasPorEstado(?string$i=null,?string$f=null):array{[$w,$t,$v]=$this->fechas('p.fecha_aplicacion',$i,$f);$e='CASE WHEN d.estado="Pagado" THEN "Finalizada" WHEN CURDATE()<=p.nueva_fecha_limite THEN "Vigente" ELSE "Vencida" END';return$this->q('SELECT '.$e.' etiqueta,COUNT(*) cantidad FROM prorrogas p JOIN adeudos d ON d.id_adeudo=p.id_adeudo WHERE 1'.$w.' GROUP BY '.$e,$t,$v)->fetch_all(MYSQLI_ASSOC);}
 public function obtenerUltimosPagosValidados(int$l=5):array{$s=$this->c->prepare('SELECT p.fecha_pago,a.matricula,a.nombre,d.periodo,p.total_pagado,p.origen FROM pagos p JOIN alumnos a ON a.id_alumno=p.id_alumno LEFT JOIN adeudos d ON d.id_adeudo=p.id_adeudo WHERE p.estado_validacion="Validado" ORDER BY p.fecha_pago DESC,p.id_pago DESC LIMIT ?');$s->bind_param('i',$l);$s->execute();return$s->get_result()->fetch_all(MYSQLI_ASSOC);}public function obtenerPeriodosDisponibles():array{return array_column($this->c->query('SELECT DISTINCT DATE_FORMAT(periodo,"%Y-%m") periodo FROM adeudos WHERE periodo IS NOT NULL ORDER BY periodo DESC')->fetch_all(MYSQLI_ASSOC),'periodo');}
}
