<?php
// Modelo: historial y aplicación transaccional de prórrogas.
class Prorroga
{
 private mysqli $conexion;public function __construct(mysqli $c){$this->conexion=$c;}
 private function base():string{return ' FROM prorrogas p INNER JOIN adeudos d ON d.id_adeudo=p.id_adeudo INNER JOIN alumnos a ON a.id_alumno=d.id_alumno LEFT JOIN usuarios u ON u.id_usuario=p.aplicada_por ';}
 private function estado():string{return 'CASE WHEN d.estado="Pagado" THEN "Finalizada" WHEN CURDATE()<=p.nueva_fecha_limite THEN "Vigente" ELSE "Vencida" END';}
 public function listarParaAdministrador(string $b='',string $periodo='',string $estado='',int $limite=10,int $offset=0):array{$pat='%'.$b.'%';$sql='SELECT p.id_prorroga,p.id_adeudo,a.matricula,a.nombre,a.correo,d.periodo,d.total,d.estado adeudo_estado,p.fecha_limite_anterior,p.nueva_fecha_limite,p.motivo,u.nombre administrador,p.fecha_aplicacion,'.$this->estado().' estado_visual'.$this->base().'WHERE (?="" OR a.matricula LIKE ? OR a.nombre LIKE ? OR a.correo LIKE ?) AND (?="" OR DATE_FORMAT(d.periodo,"%Y-%m")=?) AND (?="" OR '.$this->estado().'=?) ORDER BY p.fecha_aplicacion DESC,p.id_prorroga DESC LIMIT ? OFFSET ?';$s=$this->conexion->prepare($sql);$s->bind_param('ssssssssii',$b,$pat,$pat,$pat,$periodo,$periodo,$estado,$estado,$limite,$offset);$s->execute();return $s->get_result()->fetch_all(MYSQLI_ASSOC);}
 public function contarParaAdministrador(string $b='',string $periodo='',string $estado=''):int{$pat='%'.$b.'%';$sql='SELECT COUNT(*) total'.$this->base().'WHERE (?="" OR a.matricula LIKE ? OR a.nombre LIKE ? OR a.correo LIKE ?) AND (?="" OR DATE_FORMAT(d.periodo,"%Y-%m")=?) AND (?="" OR '.$this->estado().'=?)';$s=$this->conexion->prepare($sql);$s->bind_param('ssssssss',$b,$pat,$pat,$pat,$periodo,$periodo,$estado,$estado);$s->execute();return(int)($s->get_result()->fetch_assoc()['total']??0);}
 public function buscarDetallePorId(int $id):?array{$sql='SELECT p.id_prorroga,p.id_adeudo,a.matricula,a.nombre,a.correo,d.periodo,d.total,d.estado adeudo_estado,p.fecha_limite_anterior,p.nueva_fecha_limite,p.motivo,u.nombre administrador,p.fecha_aplicacion,'.$this->estado().' estado_visual'.$this->base().'WHERE p.id_prorroga=?';$s=$this->conexion->prepare($sql);$s->bind_param('i',$id);$s->execute();return$s->get_result()->fetch_assoc()?:null;}
 public function obtenerUltimaPorAdeudo(int $idAdeudo):?array{$s=$this->conexion->prepare('SELECT id_prorroga,id_adeudo,fecha_limite_anterior,nueva_fecha_limite,fecha_aplicacion FROM prorrogas WHERE id_adeudo=? ORDER BY fecha_aplicacion DESC,id_prorroga DESC LIMIT 1');$s->bind_param('i',$idAdeudo);$s->execute();return$s->get_result()->fetch_assoc()?:null;}
 public function obtenerAdeudosElegibles():array{$s=$this->conexion->prepare('SELECT d.id_adeudo,a.matricula,a.nombre,a.correo,d.periodo,d.total,d.fecha_limite FROM adeudos d INNER JOIN alumnos a ON a.id_alumno=d.id_alumno WHERE d.estado="Pendiente" AND d.fecha_limite IS NOT NULL ORDER BY a.nombre,d.periodo DESC');$s->execute();return$s->get_result()->fetch_all(MYSQLI_ASSOC);}
 public function buscarAdeudoElegiblePorId(int $id,bool $lock=false):?array{$sql='SELECT d.id_adeudo,a.matricula,a.nombre,a.correo,d.periodo,d.total,d.fecha_limite,d.estado FROM adeudos d INNER JOIN alumnos a ON a.id_alumno=d.id_alumno WHERE d.id_adeudo=?'.($lock?' FOR UPDATE':'');$s=$this->conexion->prepare($sql);$s->bind_param('i',$id);$s->execute();return$s->get_result()->fetch_assoc()?:null;}
 public function aplicar(int $idAdeudo,string $fechaAnterior,string $nuevaFecha,string $motivo,int $idAdmin):int|false{$this->conexion->begin_transaction();try{$a=$this->buscarAdeudoElegiblePorId($idAdeudo,true);if(!$a||$a['estado']!=='Pendiente'||$a['fecha_limite']===null||$nuevaFecha<=$a['fecha_limite'])throw new RuntimeException();$anterior=$a['fecha_limite'];$s=$this->conexion->prepare('INSERT INTO prorrogas(id_adeudo,fecha_limite_anterior,nueva_fecha_limite,motivo,aplicada_por) VALUES(?,?,?,?,?)');$s->bind_param('isssi',$idAdeudo,$anterior,$nuevaFecha,$motivo,$idAdmin);$s->execute();$id=(int)$this->conexion->insert_id;$u=$this->conexion->prepare('UPDATE adeudos SET fecha_limite=? WHERE id_adeudo=? AND estado="Pendiente" AND fecha_limite=?');$u->bind_param('sis',$nuevaFecha,$idAdeudo,$anterior);$u->execute();if(!$id||$u->affected_rows!==1)throw new RuntimeException();$this->conexion->commit();return$id;}catch(Throwable $e){$this->conexion->rollback();return false;}}
}
