<?php
// Modelo de solo lectura: consultas y resúmenes del módulo de reportes.
class Reporte
{
    public function __construct(private mysqli $conexion) {}
    private function ejecutar(string $sql,string $tipos,array $valores):mysqli_result{$s=$this->conexion->prepare($sql);if($tipos!=='')$s->bind_param($tipos,...$valores);$s->execute();return$s->get_result();}
    private function pagina(string $select,string $from,string $where,string $tipos,array $v,int $limite,int $offset):array{$sql=$select.$from.$where.' ORDER BY 1 DESC';if($limite>0){$sql.=' LIMIT ? OFFSET ?';$tipos.='ii';$v[]=$limite;$v[]=$offset;}return$this->ejecutar($sql,$tipos,$v)->fetch_all(MYSQLI_ASSOC);}
    private function contar(string $from,string $where,string $tipos,array $v):int{return(int)($this->ejecutar('SELECT COUNT(*) total'.$from.$where,$tipos,$v)->fetch_assoc()['total']??0);}
    private function p(array$f):array{$b=$f['buscar']??'';$pat='%'.$b.'%';$where=' WHERE (?="" OR p.folio LIKE ? OR a.matricula LIKE ? OR a.nombre LIKE ? OR a.correo LIKE ?) AND (?="" OR DATE(p.fecha_pago)>=?) AND (?="" OR DATE(p.fecha_pago)<=?) AND (?="" OR DATE_FORMAT(d.periodo,"%Y-%m")=?) AND (?="" OR p.estado_validacion=?) AND (?="" OR p.origen=?) AND (?="" OR p.metodo_pago=?)';$v=[$b,$pat,$pat,$pat,$pat,$f['desde'],$f['desde'],$f['hasta'],$f['hasta'],$f['periodo'],$f['periodo'],$f['estado'],$f['estado'],$f['origen'],$f['origen'],$f['metodo'],$f['metodo']];return[$where,'sssssssssssssssss',$v];}
    public function obtenerPagos(array$f,int$l,int$o):array{[$w,$t,$v]=$this->p($f);return$this->pagina('SELECT p.folio,p.fecha_pago,a.matricula,a.nombre,d.periodo,p.metodo_pago,p.origen,p.estado_validacion,p.total_pagado',' FROM pagos p JOIN alumnos a ON a.id_alumno=p.id_alumno LEFT JOIN adeudos d ON d.id_adeudo=p.id_adeudo ',$w,$t,$v,$l,$o);}public function contarPagos(array$f):int{[$w,$t,$v]=$this->p($f);return$this->contar(' FROM pagos p JOIN alumnos a ON a.id_alumno=p.id_alumno LEFT JOIN adeudos d ON d.id_adeudo=p.id_adeudo ',$w,$t,$v);}public function obtenerResumenPagos(array$f):array{[$w,$t,$v]=$this->p($f);return$this->ejecutar('SELECT COUNT(*) total,SUM(p.estado_validacion="Validado") validados,SUM(p.estado_validacion="Pendiente") pendientes,SUM(p.estado_validacion="Rechazado") rechazados,COALESCE(SUM(CASE WHEN p.estado_validacion="Validado" THEN p.total_pagado ELSE 0 END),0) monto FROM pagos p JOIN alumnos a ON a.id_alumno=p.id_alumno LEFT JOIN adeudos d ON d.id_adeudo=p.id_adeudo '.$w,$t,$v)->fetch_assoc();}
    private function d(array$f):array{$b=$f['buscar']??'';$pat='%'.$b.'%';$r=$f['recargo']??'';$w=' WHERE (?="" OR a.matricula LIKE ? OR a.nombre LIKE ? OR a.correo LIKE ?) AND (?="" OR DATE_FORMAT(d.periodo,"%Y-%m")=?) AND (?="" OR d.estado=?) AND (?="" OR d.fecha_limite>=?) AND (?="" OR d.fecha_limite<=?) AND (?="" OR (?="con" AND d.recargo>0) OR (?="sin" AND d.recargo=0))';$v=[$b,$pat,$pat,$pat,$f['periodo'],$f['periodo'],$f['estado'],$f['estado'],$f['desde'],$f['desde'],$f['hasta'],$f['hasta'],$r,$r,$r];return[$w,'sssssssssssssss',$v];}
    public function obtenerAdeudos(array$f,int$l,int$o):array{[$w,$t,$v]=$this->d($f);return$this->pagina('SELECT d.id_adeudo,a.matricula,a.nombre,d.periodo,d.fecha_limite,d.mensualidad,d.aportacion_tsu,d.atraso,d.recargo,d.total,d.estado',' FROM adeudos d JOIN alumnos a ON a.id_alumno=d.id_alumno ',$w,$t,$v,$l,$o);}public function contarAdeudos(array$f):int{[$w,$t,$v]=$this->d($f);return$this->contar(' FROM adeudos d JOIN alumnos a ON a.id_alumno=d.id_alumno ',$w,$t,$v);}public function obtenerResumenAdeudos(array$f):array{[$w,$t,$v]=$this->d($f);return$this->ejecutar('SELECT COUNT(*) total,SUM(d.estado="Pendiente") pendientes,SUM(d.estado="Pagado") pagados,COALESCE(SUM(CASE WHEN d.estado="Pendiente" THEN d.total ELSE 0 END),0) monto_pendiente,COALESCE(SUM(CASE WHEN d.estado="Pagado" THEN d.total ELSE 0 END),0) monto_pagado,SUM(d.recargo>0) con_recargo FROM adeudos d JOIN alumnos a ON a.id_alumno=d.id_alumno '.$w,$t,$v)->fetch_assoc();}
    private function a(array$f):array{$b=$f['buscar']??'';$pat='%'.$b.'%';$w=' WHERE (?="" OR a.matricula LIKE ? OR a.nombre LIKE ? OR a.correo LIKE ?) AND (?="" OR a.estado=?) AND (?="" OR a.carrera=?) AND (?="" OR a.grupo=?)';$v=[$b,$pat,$pat,$pat,$f['estado'],$f['estado'],$f['carrera'],$f['carrera'],$f['grupo'],$f['grupo']];return[$w,'ssssssssss',$v];}
    public function obtenerAlumnos(array$f,int$l,int$o):array{[$w,$t,$v]=$this->a($f);return$this->pagina('SELECT a.matricula,a.nombre,a.correo,a.carrera,a.grupo,a.estado',' FROM alumnos a ',$w,$t,$v,$l,$o);}public function contarAlumnos(array$f):int{[$w,$t,$v]=$this->a($f);return$this->contar(' FROM alumnos a ',$w,$t,$v);}public function obtenerResumenAlumnos(array$f):array{[$w,$t,$v]=$this->a($f);return$this->ejecutar('SELECT COUNT(*) total,SUM(a.estado="Activo") activos,SUM(a.estado="Inactivo") inactivos,COUNT(DISTINCT a.carrera) carreras,COUNT(DISTINCT a.grupo) grupos FROM alumnos a '.$w,$t,$v)->fetch_assoc();}public function opcionesAlumnos():array{return['carreras'=>array_column($this->conexion->query('SELECT DISTINCT carrera FROM alumnos ORDER BY carrera')->fetch_all(MYSQLI_ASSOC),'carrera'),'grupos'=>array_column($this->conexion->query('SELECT DISTINCT grupo FROM alumnos ORDER BY grupo')->fetch_all(MYSQLI_ASSOC),'grupo')];}
    private function r(array$f):array{$b=$f['buscar']??'';$pat='%'.$b.'%';$estado='CASE WHEN d.estado="Pagado" THEN "Finalizada" WHEN CURDATE()<=p.nueva_fecha_limite THEN "Vigente" ELSE "Vencida" END';$w=' WHERE (?="" OR a.matricula LIKE ? OR a.nombre LIKE ? OR a.correo LIKE ?) AND (?="" OR DATE_FORMAT(d.periodo,"%Y-%m")=?) AND (?="" OR DATE(p.fecha_aplicacion)>=?) AND (?="" OR DATE(p.fecha_aplicacion)<=?) AND (?="" OR '.$estado.'=?)';$v=[$b,$pat,$pat,$pat,$f['periodo'],$f['periodo'],$f['desde'],$f['desde'],$f['hasta'],$f['hasta'],$f['estado'],$f['estado']];return[$w,'ssssssssssss',$v,$estado];}
    public function obtenerProrrogas(array$f,int$l,int$o):array{[$w,$t,$v,$e]=$this->r($f);return$this->pagina('SELECT p.id_prorroga,a.matricula,a.nombre,d.periodo,p.fecha_limite_anterior,p.nueva_fecha_limite,'.$e.' estado_visual,p.motivo,u.nombre administrador,p.fecha_aplicacion',' FROM prorrogas p JOIN adeudos d ON d.id_adeudo=p.id_adeudo JOIN alumnos a ON a.id_alumno=d.id_alumno LEFT JOIN usuarios u ON u.id_usuario=p.aplicada_por ',$w,$t,$v,$l,$o);}public function contarProrrogas(array$f):int{[$w,$t,$v]=$this->r($f);return$this->contar(' FROM prorrogas p JOIN adeudos d ON d.id_adeudo=p.id_adeudo JOIN alumnos a ON a.id_alumno=d.id_alumno ',$w,$t,$v);}public function obtenerResumenProrrogas(array$f):array{[$w,$t,$v,$e]=$this->r($f);return$this->ejecutar('SELECT COUNT(*) total,SUM('.$e.'="Vigente") vigentes,SUM('.$e.'="Vencida") vencidas,SUM('.$e.'="Finalizada") finalizadas,COUNT(DISTINCT d.id_alumno) alumnos FROM prorrogas p JOIN adeudos d ON d.id_adeudo=p.id_adeudo JOIN alumnos a ON a.id_alumno=d.id_alumno '.$w,$t,$v)->fetch_assoc();}
    private function c(array$f):array{$b=$f['buscar']??'';$pat='%'.$b.'%';$w=' WHERE (?="" OR c.folio LIKE ? OR a.matricula LIKE ? OR a.nombre LIKE ? OR a.correo LIKE ? OR c.asunto LIKE ?) AND (?="" OR c.tipo=?) AND (?="" OR c.estado=?) AND (?="" OR DATE(c.fecha_registro)>=?) AND (?="" OR DATE(c.fecha_registro)<=?)';$v=[$b,$pat,$pat,$pat,$pat,$pat,$f['tipo'],$f['tipo'],$f['estado'],$f['estado'],$f['desde'],$f['desde'],$f['hasta'],$f['hasta']];return[$w,'ssssssssssssss',$v];}
    public function obtenerAclaraciones(array$f,int$l,int$o):array{[$w,$t,$v]=$this->c($f);return$this->pagina('SELECT c.folio,c.fecha_registro,a.matricula,a.nombre,c.tipo,c.asunto,c.estado,u.nombre atendida_por,c.fecha_atencion',' FROM aclaraciones c JOIN alumnos a ON a.id_alumno=c.id_alumno LEFT JOIN usuarios u ON u.id_usuario=c.atendida_por ',$w,$t,$v,$l,$o);}public function contarAclaraciones(array$f):int{[$w,$t,$v]=$this->c($f);return$this->contar(' FROM aclaraciones c JOIN alumnos a ON a.id_alumno=c.id_alumno ',$w,$t,$v);}public function obtenerResumenAclaraciones(array$f):array{[$w,$t,$v]=$this->c($f);return$this->ejecutar('SELECT COUNT(*) total,SUM(c.estado="Abierta") abiertas,SUM(c.estado="En revisión") revision,SUM(c.estado="Resuelta") resueltas,SUM(c.estado="Rechazada") rechazadas,SUM(c.estado IN("Abierta","En revisión")) pendientes FROM aclaraciones c JOIN alumnos a ON a.id_alumno=c.id_alumno '.$w,$t,$v)->fetch_assoc();}
}
